apiVersion: v1
kind: Secret
metadata:
  name: skilllink-secrets
  namespace: skilllink
type: Opaque
stringData:
  DATABASE_URL: "postgresql://skilllink:skilllink123@postgres:5432/skilllink_db"
  POSTGRES_PASSWORD: "skilllink123"
  JWT_SECRET: "skilllink-jwt-secret-2026-production"
  JWT_REFRESH_SECRET: "skilllink-refresh-secret-2026-production"
